### PR TITLE
Refactor & Rename

### PR DESCRIPTION
**Pull request by RaySingerNZ**
- [ ] Refactor Person class to reduce code duplication.
- [ ] Rename delegate to match MS naming conventions.

### CODE REVIEW

**Comment by nevercast** [comment]
Darn it @RaySingerNZ you Pull Requested in to your own Repo. This is meant to go to @nateforsyth :+1:

**Comment by RaySingerNZ** [comment]
@nevercast Ah! That's what happens when you're in a rush. In good news the baby scan went well. Phew!

**Comment by nevercast** [comment]
That's very good news! Hooray 
How long now?

**Comment by RaySingerNZ** [comment]
@nevercast tomorrow! But we're both thinking it's going to be a bit later.

**Pull request closed without merging**
